title: Klimaschutz Rohrbach
description: Website der Klimaschutz-Taskforce Rohrbach a.d. Ilm
author: "Bürgerarbeitskreis Energie Rohrbach a.d. Ilm"

theme: minima

base_url: /klimaschutztag-rohrbach-2023

# Minima social links
#rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: True

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/veranstaltungstermine.md
  - _pages/about.md
  - _pages/impressum.md
  #- _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor
