title: Klimaschutztag Rohrbach 2023
description: Website für den Klimaschutztag in Rohrbach a.d. Ilm am 26.03.2023
author: "Bürgerarbeitskreis Energie Rohrbach a.d. Ilm"

theme: minima

base_url: /klimaschutztag-rohrbach-2023

# Minima social links
#twitter_username: xurxosanz
#github_username: jsanz
#linkedin_username: jsanz
#rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  #- _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
