version: '3'

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
      - jekyll:/usr/local/bundle
    ports:
      - '4000:4000'
      - '35729:35729'
    command: [ "bundle", "exec", "jekyll", "serve", "--force_polling", "-H", "0.0.0.0", "-P", "4000", "--livereload", "--livereload-port", "35729", "--baseurl", "/gh-pages-minima-starter" ] 

volumes:
    jekyll:
